name: release

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - name: DigitalOcean App Platform deployment
      uses: digitalocean/app_action@main
      with:
        app_name: orca-app
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
